spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 121314
    url: jdbc:mysql://localhost:3306/wupupupu
mybatis:
  configuration:
    map-underscore-to-camel-case: true
